### ISSUE TITLE
install nits

### ISSUE THREAD

**Issue by f451-fbsd** [ronaldklop/fakertc#1]
Hi, thank you for creating this

On install, fakertc doesn't make the file it needs in order to work.

# service fakertc start
Set RTC from: /var/db/fakertc: /usr/local/etc/rc.d/fakertc: WARNING: /var/db/fakertc is not readable

fix is:

# touch /var/db/fakertc
# service fakertc start
Set RTC from: /var/db/fakertc: Fri Aug 26 14:58:34 UTC 2022
.

[1] 14.0-CURRENT #1 main-n257229-e9a2e4d1d28: Wed Aug 10 16:00:33 B
ST 2022
[2] # git -C /usr/ports rev-list --first-parent --count main
592994

**Comment by ronaldklop** [comment]
Hi, thanks for your report.
It is a bit counter intuitive but actually _stop_ should be run before _start_. On shutdown stop runs and saves the date. On boot start runs and it restores the date. So running start without stop does not make sense technically. But I understand that it is intuitive to start the tool after installation so I'm thinking about checking for a not existing file and let start save the date if the file does not exist. That seems more user friendly to me than a warning.

About your solution. When you "touch" the file it creates an empty file. Then start incidentally runs "date -u " (with the whitespace because the file is empty) and that just prints the current date. So it looks better but it is just a cosmetic difference.

I already created a patch but will need to test a little bit more.
